# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
            framework: net8.0
            output: publish/linux
          - os: windows-latest
            rid: win-x64
            framework: net8.0-windows8.0
            output: publish/windows

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src/Win2Mqtt.App/Win2Mqtt.App.csproj

      - name: Publish
        run: dotnet publish src/Win2Mqtt.App/Win2Mqtt.App.csproj -c Release -f ${{ matrix.framework }} -r ${{ matrix.rid }} --self-contained -o ${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win2mqtt-${{ matrix.rid }}
          path: ${{ matrix.output }}
